site_name: Tendência Perfeita
theme:
  font:
    text: Quicksand
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  name: material
  logo: assets/chart.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yanBrandao
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yanbrandao/

copyright:  Copyright &copy; 2023 <a href="https://github.com/yanBrandao" target="_blank" rel="noopener">Yan Tapajós</a>